import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import './LoadPlaylist.css'
import axios from 'axios';
import HomeHeader from './components/HomeHeader';

const NEW_TRACK_API_ENDPOINT = 'http://localhost:5000/newtracks'

function LoadPlaylist() {
  const [token, setToken] = useState("");
  const [ID, setID] = useState("");
  const [playlistID, setPlaylistID] = useState("");
  const [GETReturn, setGETReturn] = useState(false);
  const [songs, setSongs] = useState({});
  const [URIs, setURIs] = useState([]);
  const [theme, setTheme] = useState("");
  
  // set token
  useEffect(() => {
    if (localStorage.getItem("accessToken")) {
      setToken(localStorage.getItem("accessToken"));
    }
  }, []);

  // get user id once token is set
  useEffect(() => {
    if (token === "") {
      return;
    }
    axios.get('https://api.spotify.com/v1/me', {
      headers: {
        Authorization: `Bearer ${token}`
      }
    })
    .then((response) => {
      setID(response.data.id);
    })
  }, [token]);
  
  // MOVE THIS TO HANDLECREATEPLAYLIST????????????????
  // POST new tracks to new spotify playlist
  useEffect(() => {
    const ADD_SONG_ENDPOINT = `https://api.spotify.com/v1/playlists/${playlistID}/tracks`;
    if (playlistID === "") {
      return;
    }
    const request = axios.post(ADD_SONG_ENDPOINT, 
      {
        "uris": URIs,
      },
      {
        "headers": {
          Authorization: `Bearer ${token}`
        }
      });
    return request;
  }, [playlistID])

  // GET newly generated tracks from songList.csv
  useEffect(() => {
    setURIs([])
    // async function setState(set, state) {
    //   await set(state);
    // }
    async function fetchData() {
      const request = await axios.get(NEW_TRACK_API_ENDPOINT);
      // setState(setSongs, request.data);
      setSongs(request.data)
      let uri = []
      for (let i = 0; i < Object.keys(songs.data.song).length; i++){
        uri.push(`spotify:track:${songs.data.spotify_id[i]}`);
      }
      // setState(setURIs, uri);
      setURIs(uri);
      // setState(setTheme, songs.data.theme[0]);
      setTheme(songs.data.theme[0]);
      console.log(theme);
      // console.log(songs)
      if (request?.data) {
        setGETReturn(true);
      }
      // let req = request?.data ? setGETReturn(true) : null;
      return request;
    }
    fetchData();
    // setGETReturn(true);
  }, [])

  const handleCreatePlaylist = () => {
    const CREATE_PLAYLIST_ENDPOINT = `https://api.spotify.com/v1/users/${ID}/playlists`;

    fetch(CREATE_PLAYLIST_ENDPOINT, {
          'method':'post',
          body: JSON.stringify({
              "name": `${theme}`,
              "description": `songs of ${theme} generated by Thematic Music Recommender`,
              "public": false
          }),
          headers: {
            Authorization: "Bearer " + token
          }
        })
        .then((response) => response.json())
        .then((data) => {
          // console.log(data.id);
          setPlaylistID(data.id);
        })
        .catch(error => console.log(error));
  }

  return (
    <div className='loadPlaylist'>
        <HomeHeader></HomeHeader>
        <div className='loadPlaylist__container'>
            <h1>Generating Your New Playlist...</h1>
            {GETReturn ? <button>Display new songs</button> : <p>Loading...</p>}
            <button onClick={handleCreatePlaylist} className='loadPlaylist__import'>Import your new playlist to your Spotify account</button>
            
            {songs?.data ? <p>{songs.data.song[0]}</p> : null}
            
        </div>
        <Link to='/playlists'>
                <button className='loadPlaylist__another'>Create Another Playlist</button>
        </Link>
    </div>
  )
}

export default LoadPlaylist