import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import './LoadPlaylist.css';
import axios from 'axios';
import HomeHeader from './components/HomeHeader';

const NEW_TRACK_API_ENDPOINT = 'http://localhost:5000/newtracks';

function LoadPlaylist() {
  const [token, setToken] = useState("");
  const [ID, setID] = useState("");
  const [playlistID, setPlaylistID] = useState("");
  const [GETReturn, setGETReturn] = useState(false);
  const [songs, setSongs] = useState({});
  const [URIs, setURIs] = useState([]);
  const [theme, setTheme] = useState("");
  
  // set token
  useEffect(() => {
    if (localStorage.getItem("accessToken")) {
      setToken(localStorage.getItem("accessToken"));
    }
  }, []);

  // get user id once token is set
  useEffect(() => {
    if (token === "") {
      return;
    }
    axios.get('https://api.spotify.com/v1/me', {
      headers: {
        Authorization: `Bearer ${token}`
      }
    })
    .then((response) => {
      setID(response.data.id);
    })
  }, [token]);
  
  // POST new tracks to new spotify playlist
  useEffect(() => {
    const ADD_SONG_ENDPOINT = `https://api.spotify.com/v1/playlists/${playlistID}/tracks`;
    if (playlistID === "") {
      return;
    }
    axios.post(ADD_SONG_ENDPOINT, 
      {
        "uris": URIs,
      },
      {
        "headers": {
          Authorization: `Bearer ${token}`
        }
      });
  }, [playlistID])

  // GET newly generated tracks from songList.csv
  useEffect(() => {
    async function fetchData() {
      const request = await axios.get(NEW_TRACK_API_ENDPOINT);
      setSongs(request.data)
    }
    async function fetch() {
      await fetchData();
      setGETReturn(true);
    }
    fetch();
  }, [])

  // set theme, URIs once songs data is set
  useEffect(() => {
      if (songs?.data) {
          setTheme(songs.data.theme[0]);
          let uri = []
          for (let i = 0; i < Object.keys(songs.data.song).length; i++){
            uri.push(`spotify:track:${songs.data.spotify_id[i]}`);
          }
          setURIs(uri);
      }
  }, [songs])

  const handleCreatePlaylist = () => {
    const CREATE_PLAYLIST_ENDPOINT = `https://api.spotify.com/v1/users/${ID}/playlists`;

    fetch(CREATE_PLAYLIST_ENDPOINT, {
          'method':'post',
          body: JSON.stringify({
              "name": `${theme}`,
              "description": `songs of ${theme} generated by Thematic Music Recommender`,
              "public": false
          }),
          headers: {
            Authorization: "Bearer " + token
          }
        })
        .then((response) => response.json())
        .then((data) => {
          setPlaylistID(data.id);
        })
        .catch(error => console.log(error));
  }

  return (
    <div className='loadPlaylist'>
        <HomeHeader/>
        <div className='loadPlaylist__container'>
            {GETReturn ? <h1>Complete!</h1> : <h1>Generating Your New Playlist...</h1>}
            {GETReturn ? 
                <button onClick={handleCreatePlaylist} className='loadPlaylist__import'>
                    Import your new playlist to your Spotify account
                </button> 
                : 
                <p>Please Wait</p>
            }        
            {GETReturn?
            <Link to='/playlists'>
                    <button className='loadPlaylist__another'>Create Another Playlist</button>
            </Link>
            :
            null
          }    
        </div>
    </div>
  )
}

export default LoadPlaylist